[features]
seeds = false
[programs.localnet]
mysolanaapp = "3o9NcFWUTHAbHnjsZvuMYRWjWU6Zy643BHFwJR745iYa"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/aaron/.config/solana/id.json"

[scripts]
test = "yarn run mocha -t 1000000 tests/"
